version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app1:
    build: .
    container_name: app1
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PART=left
    depends_on:
      - rabbitmq

  app2:
    build: .
    container_name: app2
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PART=right
    depends_on:
      - rabbitmq

  merger:
    build: .
    container_name: merger
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./wwwroot/ProcessedImages:/app/wwwroot/ProcessedImages 
