version: "3.8"

networks:
  custom_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - custom_network
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  app:
    build: .
    networks:
      - custom_network
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    deploy:
      replicas: 10
    restart: always
